### ISSUE TITLE
Create an API for downloading the data

### ISSUE THREAD

**Issue by bryan-harter** [IMAP-Science-Operations-Center/SDS-in-a-box#7]
We can just start with a simple API for now that takes in only "filename=XXXX" as input, and we query the database for the file location.  The API can return a signed url where the user can access that file.

**Comment by tech3371** [comment]
I can take this task since I have done something similar on EMM. 

Couple questions.
Since we are replacing database with opensearch, we are querying data from opensearch to get the file location. Is that right?
And once we know the location of the file, we generate a pre-signed url to allow download?

**Comment by bryan-harter** [comment]
Yup, that's what I was thinking!

**Comment by tech3371** [comment]
https://github.com/IMAP-Science-Operations-Center/SDS-in-a-box/pull/20
